vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        menu_images:
            uri_prefix: /image/menu
            upload_destination: '%kernel.project_dir%/public/image/menu'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true