vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        menu_images:
            uri_prefix: /image/menu
            upload_destination: '%kernel.project_dir%/public/image/menu'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        user_images:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            